version: "3"
services:
  www:
    image: httpd:latest
    ports:
      - 8001:80
    volumes:
      - ./:/usr/local/apache2/htdocs
  db:
    image: mysql:latest
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=rezervak
    volumes:
      - ./db:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306