<?php


declare(strict_types=1);

namespace App\Modules\admin\Presenters;

use Nette;
use Nette\Application\UI\Form;


final class DiscountCodesPresenter extends SecurePresenter
{

    private $id;
    public function __construct(
        private Nette\Database\Explorer $database
    )
    {}

    public function beforeRender()
    {
        parent::beforeRender(); // TODO: Change the autogenerated stub

    }

    public function actionShow() {
        $discountCodes = $this->database->table("discount_codes")->where("user_id=?", $this->user->id)->fetchAll();
        $this->template->discountCodes = $discountCodes;
    }

    public function actionEdit(int $id) {
        $this->id = $id;
        $discountCode = $this->database->table("discount_codes")->where("id=?", $id)->fetch();
        $this->template->discountCode = $discountCode;
    }

    protected function createComponentForm(): Form
    {
        $form = new Form;
        $form->addHidden("action");
        $form->addText("code", "Code");
        $form->addCheckbox("active", "Aktivní");
        $form->addSubmit("save", "Vytvořit");

        $form->onSuccess[] = [$this, "formSucceeded"];

        return $form;
    }

    public function formSucceeded(Form $form, $values)
    {
        $show = $values->active ? 1 : 0;
        $status = false;
        switch ($values->action) {
            case "create":
                $status = $this->database->table("discount_codes")->insert([
                    "user_id" => $this->user->id,
                    "code" => $values->code,
                    "active" => $show,
                ]);
                break;
            case "edit":
                $status = $this->database->table("discount_codes")->where("id=?", $this->id)->update([
                    "code" => $values->code,
                    "active" => $show,
                ]);
                break;
        }
        if ($status) {
            $this->flashMessage("Vytvořeno", "success");
            $this->redirect("DiscountCodes:show");
        } else {
            $this->flashMessage("Nepodarilo se vytvořit", "error");
        }
    }


}
