<?php


declare(strict_types=1);

namespace App\Modules\admin\Presenters;

use Nette;


final class HomePresenter extends SecurePresenter
{

    public function __construct(
    )
    {
    }

    protected function beforeRender()
    {
        parent::beforeRender(); // TODO: Change the autogenerated stub

    }
}
